baseURL = 'https://nsd-highpublic.ceo-suo.com/'
languageCode = 'ko-KR'
title = '낙성대 하이퍼블릭 에르 할인 정보'

[params]
  isAdsEnabled = true
  adsTelegramId = "ggyuvely"

  description = '낙성대 하이퍼블릭 에르는 관악구에 있는 하이퍼블릭 매장으로, 봉천·낙성대 일대에서 고급 테이블 문화를 즐기려는 분들에게 알려져 있다.'
  author = '두리'
  datePublished = "2026-08-18T08:10:00+09:00"
  dateModified = "2026-08-18T08:10:00+09:00"
  [params.store]
	tel = "010-8306-5747"
  location = "낙성대"
	locationEn = "NSD"
  name = "에르"
	nameEn = "ER"
	nameIs = "는"
	category = "하이퍼블릭"
	categoryEn = "Highpublic"
	categoryIs = "는"
	address = "서울 관악구"
	googleMapSrc = "https://www.google.com/maps?q=서울+관악구&output=embed"

enableRobotsTXT = false
cleanDestinationDir = true

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
